apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:NOD6lBSX1QtPoY1oqdIza/aGHH+FUU30ENR14RqTpP7rtTWS49TzTyJOFZwCq1ILzh4C1MKkTRF2M+tzWlwXomG9WVgRouWEBixznCMDjgjCxUWIqocUVf17vq8uyWxqQHGAa1IpeffEhcNqjq0tx33vg7cEVqoPwwKUEtP/DFEjBFZb1sWVuGZdjwR89vOt8N8597NZmx991fJ7Neoltn/OqB4Tumc5filrpyjscjVtF3QjigVkeBkE5fOQuMQ/doB0/tTzJHeKnGh9/u9cYf/R/tV0bdMTEOniQm/YNTG7RsRm9fGeuepd4hyUV1JlcbEQDWURNkHTdipl7Dt+JKrTJWAqk/7d0XJ9MTu51f5NtTIMJ49L7W3yNXgAFT8j,iv:zwaNdIapgVTH70DzDQLIFSBjbvWuL3IsR0hjxu/CoME=,tag:ZS4VCfFsuAgh4Q0uVCq/ow==,type:str]
    identity.pub: ENC[AES256_GCM,data:jzJDV79QpOhJAnlYfDtdkZKLxrBNm3UBZJOSTxGiZ6otoKO2IsTQwhBjpn0Q1s0X5Pblek58kA4dY0nDpKMxeXZwB5Vel8WOZfQOjYR5TbB30fzXpYH6IuQZLTesQrGt+IxpOdI91nUiUgxC5QHPqxswO46Tnw5ocPV7FlgAGscVhtatw8GrNJxmnVot77mSTFEu0cNTZ8Po829Aq7N393Fip78N/L9tByK4sKANt25Y62A6NKQoTwt0e+tIX+8ze+pl5OXJVqFoTgevUg==,iv:TUD9c854bm40QDk2FziqrJ5Itw5tQzVByclfo0qBEac=,tag:kGAl03d9T46U9RKtxEXI4g==,type:str]
    known_hosts: ENC[AES256_GCM,data:leItK3xKVPDt5soBXkfcNHuSvCw7vIkMjBnCCEffrhcclA7zIWr1EaQwCesnSGkemDaQyqvDhBvroR3uNQQVGQ5Ky5Mzt1BV7j9KzafnAQvwFiwd1SvxTPSg+GJeedfxAme3Zu5VTMM51Tg7lSlb2GEikaEAojI5O6g4VS3EkzPRXBNnEYWTRxpNhTswXOWAML2w+/VGFd6Mya/k0uipDmE8lMwFpIs+4bez,iv:fxCC6Cj6bk3F193aWECPkZk8+98W4RZiFPvi71jiznw=,tag:hKoFWvqa/ySO103eDejqFg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1h4wse77xcknyuzq798eg5cvl30npk5lxzk05cfwmpyhnz7vl39psqavxdm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMEY1dm5WQVdBa3padVAy
            aVdMcGIzUkhuQ2M0Mks4OE9OVVh2RmlOS1VBCm5EcDgxWCs4K3liWUVOc3lHMlRm
            YVhMcXBoVG1DMkhuWks4MXI0S09nUmsKLS0tIEY0Z1hBdDNYZCs4Q1pFeEZYeWhp
            NEYraGpwOE1jbUhSNmc3SngxalFZajQK02Um0TQLvdYpaL/i+Pr2EMyjgX9CYKKJ
            yQ4auH8D60jJjUk+K9IUa4U4T4ppC4lC1LTUbjzcPs3ipdFdrQC8gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T13:57:14Z"
    mac: ENC[AES256_GCM,data:ONOE5TYECjMcI9q/u1Iv3QuN6A/KsJypY7NIqgN8A7VkPPGdNIJjfXKFGwRilfRSp9m1/6wpzSm79A1xaaRhNL6UPy0btt6qAiEhKDOYSaJaZcCjzaHJoJIc9/YHXUtmgtADAq6U2Hf89KzHj0ZlmlvIT4SGrSBDQKfHyX+38Gg=,iv:CuCSCYIZzmFsww+RHGuubdDUUkTeGl70wqbkpXHEz5s=,tag:u61/NhQy5WpuY8zMStRMzA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
