apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:P7Uo0OOMFblQSuVZxvVDb9EKdYR80BSoHAEX5djGy5nR65DwpTgV6oAcyZMN9qps5bTQEyo8XVZ3tevonslD17AsjKUbFQMslF8oxku/3QGdisSySO8YC48GYPfoWJl6QlpEzX6FaYXGjY+5E4IMs1Yz9W/AMV8IROHRckabOGliHlRBde0joov9C9FjtPtppfn75s9OEzt59NEPLTidc0CwX5tnVo18s9eqpiRvtSuVz9xfg9jjHJmDFEeT0Ka9ODnddRxUEcLAPasJifpTDtRQ4A6reniDXkor1B0ALXHKRXCbGAh6tXWkKZPjGBeMALEvr+dlWkj99CU0/7jaP3r17oL47wCxq11GL0QrL8dmzDpd7vGQOjE+gDxW/NpM,iv:N1FBzgONKqNEPhGyuvMnq8RIon04b5+JeKUMy9B9L94=,tag:LZJp5ryGiRPm6yKDgxxwGw==,type:str]
    identity.pub: ENC[AES256_GCM,data:Nhzn6o2ShO6h1/FlB2QsYRHi+lidro7vh6NmyC4A2zZPc2xRkiHA4W++8EA5V+F3cQs4VQlP6kRs86ySWF4BLMKnyZCc4yUeS79RHW8q4dsn7ZX5nTHRCPH2KKOlr+FBH/b7DA46dUnrS0pQLAKfJntsyJnhXPDPY7waRgy2IbAsSI0+SD2nfUE67DzT4oH9J0QMyFmeSPT/M8LXaUXfdOh6zetOUydrStVE+3vQ5lSTQSOzhMpXGm0ONOYPkMTGGp6NvPQf8idjQRz1Lg==,iv:LbNJUgF+oGkYxZ/j4ty/96xcUm04ftk/qguXFopzK3w=,tag:SXr+lwIr6/WnfZVOX9QnHw==,type:str]
    known_hosts: ENC[AES256_GCM,data:w7uMifJKsycOVtXeDR++ydAhxOvaHQtM8GFiUPpH4p9v1Jjh/S/N2uVvENm0mSKvEKtOqw14RsDU9+BJLL9fz/wqBBlHOfUIbqUYAHRGUmPV6OHGY8RXyXayItVGKJgg/j9PNFtmG3RcrLZAwkMpWQvTLFuriIOTIWLp4GKvcekgTeLPxYxIlbBx8UbJeFoNf+AdIOWUHHm9S+bSNxGthbXZX4EQsfpSh5jS,iv:sTzrdcyQ4O+9DD6jN86ruNuCcju2deZKSfldBGC9018=,tag:09Z5DVsFgrv9OzU6SU9sqQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1h4wse77xcknyuzq798eg5cvl30npk5lxzk05cfwmpyhnz7vl39psqavxdm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQUQxdkhiMUUzOGdJcThk
            Nkd2OFpRTHJ6UHlVb3FSWXBjcloySVZQdlVFClBhM1Z6Q0VOcGNOQVRGWlRFNkFp
            RDVnMmwrTE9jcGNidE5sOW1CV0llbjQKLS0tIHBMeUVTcFowcnZoa3NJSUthdGxT
            dkpxNHJ1VElCU3VIeEpRbjgyNk1TYWsKCYiBP3nICLYes/pPTvdklH5uZDMtCYG8
            +f0MQjQY5Uocz5XgB07awx1C6ewSlIjrHP/cgxurpwrRTd8drAKKSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T20:36:10Z"
    mac: ENC[AES256_GCM,data:1MpfTpaFzbFyM9w6HAnMjqQw92InBDGiCioVaVViHXxk5OibvFdsChN0G9tpzkI9GXBOqPGciI0w5EDg3MM3Hhz9NYR7YA4XV5gEptGc83wMU1hsqGRPlatWBqQzhLUudfPsh+QfvtWeR9FlTuMNGeqKBpVV1RnnFKgYsomYbp8=,iv:3NNbErVT+H69U+vo9HZ64203S6NgjWYgbAhWPw33juI=,tag:iAbUfGGsL7cbMD0Sr54ZMA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
