apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:z2EVDhQa+3K6ZWAjRK1AuIkrEF2vG6NTb+bae4xvplTNAgoMOAIjZyTkeoqvysk8WX7xX7cKvr6O8PsXBSQbImFVZqepz74vGI6UQvs7o6ggH4XAg4GQnRqzuXHZ3VWyv9Q9fHQFhwmBbmyw9O88NmoHcfu7pmUQRxpl1IPqiLbcOvTarVGDJJJYXI/a7DhGxadS2QlVTBjuKW2p5Zn5AYkyHZkdmViDp8yUBep+GqcDrYL/vgnKX7TeWDfmzArGxIRL276pi7eg/JZmAtp9p2md8XphLl1YroIG0O6RPpFPrXvNuWM8bFt45sA0jBOthKGv5lmr2gESA80U3/srUJvXoDHilJ1JUwfRmmSeZ552+tLPhYR1Gh5M7wSAD3QV,iv:txeKyQjUTdevhzfl4ba2nQ4waeD9Xo/WuCwWRecVRjY=,tag:rojuypwAim7rMr2CatnSgg==,type:str]
    identity.pub: ENC[AES256_GCM,data:+6V43E6sngYGm7lSOHaQpeHzaYWO8mVkM6lRg4Wtv8zWiaDSKjU4lMkrBWA+MFEN9GywKv4gQhwGXofKpKJ98IpKLtv+J8lNSR0swf092MPdRtNqENRASgTP6BKgHJusmKI2aMIXy/08f9OQ0oy97ejQwCPopRyCuShuAIITac9iN0mz9Rbf5jHXooRGkioVbqvRV8+sUBmcyOYXkD9gHCFnUR0dULKVK6vOpQOUa4oquQpImpxgzXPuyqDRhAx21gVyaGzYjTNiHSemZw==,iv:MU0CK9cGUQgkTZgPWsyS2ZzhVHyb7ToTshshsn3WHIU=,tag:wc/fo/X1uZ1V7rBC9xU1RQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:DKusPgLmRzJTnsRcvZ5e4ZhF0LkCD4iddUCZPh9haOoaIFFgEKZEzmlPyFt+zJUsn132U8vKQB4IALiChUZVT4D4Z/8sJZdBxXaDJ1VLNKTbd0cFv1wSmxX3jMmn2BVEPZXfoUhnej4xfhoH4g/zPG89Pm4pdHOo2x3u8kgO+GnXC7fP/TcdbQTBxTgTL4L/j42Ai2u5rYYOQBss0nej/fKIvZ5iEP2EnVJX,iv:fsLVadWo9VVfoV4epS5RraM3X8WXT4ev5FuFYym7+Xk=,tag:FjrjCDZ/K5mKzO6UL5y3JQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1h4wse77xcknyuzq798eg5cvl30npk5lxzk05cfwmpyhnz7vl39psqavxdm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBickxNQ1B3aWE4WVEvRHZB
            eC9Sb3NneVlKdDdTalZsdDNGTXk0M0ZoNENvCitkWW5JYW5OODFrQTU0YjVVQU13
            Mkx6Q3NwbVAvd2NuZmV1OW9pZWlzWVEKLS0tIHpYam9FanQyUEtSbi9udXVTRVp5
            TUJBWnE1a2xaWmdoSXdKTWJ5OGlzbm8KMLfYK1gaAcKe8S5LfjcPw3NEMOl6wnxo
            dH0Z8rcJC0sPx7HEVU7m1mwdKT3Ma6AWK0ZN9tlexkwIXZtoEO/0qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T12:10:12Z"
    mac: ENC[AES256_GCM,data:pwjB7ElKAqBiqI8njxMhcCFrClVMX3lxLMMwnRRkNG4Tm18+L+cWKcDktSiwTp7DJLSQyVjV8rcziGLL66JpuK+NGFkqhNwMT7cxqD3oRYQ98EY6QC2MZpqOFS3hLptxOekV1PBiyUq3QxMfNU/tkALmydHVTFWPKmYoSHr2P0Q=,iv:k5xS2wP+OVs5p6WKtF2iG0bAH0pa7/8eeHtbk1nohAc=,tag:OmvAIog2K7FWIuBOxsca2Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
