apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:brDExA7xPvWUAoe8l9Wr0rMU3bth3s9BxDxJrsPsuki+lvZXfbpKmU1En8IO3Of/A3f9f1K+dfmHh2QLm+1n1RD+g3H7+YCjTrNdLuCO/VZZ9fcM+MjN8gvA1mT+gGF/lp3FF2Y2TN9pNXaqxAWGiM2HFn8GjRKw5l8Ch5YReMZrvy32DMuG41CsfnbLlc/D9N67yIrUc4m5V33sHnsjy2fx+Zti4rtj2P+YrA/8dhC2rPspY+xWJDGzXzx4fWavfpHLYQ9u6Mkc97Gwlo22YNE9jSXjiKsV8/F6V7uhtZAbaA5BXPTz3gCarbDBxLOTG4HyUDsfcw0I915WnTlAdyBOBgSFxcCR6KjG086rnFFQrKwX8boHD6OOWZ9+x1Z4,iv:i6KqvhnHaG8OMRxTBzK386G6wV7t9lKIYcQNHRdPFfE=,tag:lTY2jB5+2qrJr3M55IAmQA==,type:str]
    identity.pub: ENC[AES256_GCM,data:l6M+DGkmM/zVcTeTdHhzNNPvgyVqGjeaYpaazqd36d2/BRJtC3Wlw09sjhItyvyXHzSC68dDMdwJZ7xrWwVXm39if+ogmHqGOMBJlak8OgjxITLqAJZLlpua8nkWqn+JXsM1hgzfAFB1DKGWL9LQ0cVz5C2G8qFittCcqA0YGbCYcU0qGHuPCzhsgcWcx2/T4JyC3a0thWDODt4A8dhasPpFh/00cijME5XAXKQ1OoC3lWed9KMPZ/f5phV3b8j+tIB1M5N3KgMe72Yjxg==,iv:LcLH4wPbyqeYaYy0CFl2x28hEZljyWh9bJIZJKv1osY=,tag:t0Dlt2afu2/7txyMWEXvYA==,type:str]
    known_hosts: ENC[AES256_GCM,data:DRD55F/QakQ5Q16Nm2jELabhZjp6+aHgJEXcoZWAyEXNUoKzLXChTxhVQi/CXAh8Cyu3aLG0I6bX1hK7hgeeDbmUSSbHKZyymTCREdOjSrivITsIU2kXbSg6C1A4OLaWzLbeqXY0K5LQHHjvHyq3H6MR2SmwJdddvUHLRUxecPsdx9QwWOUh8PoUpTydE/ks5YrSn93KUSh4Rn9X7Od656OhvqKNqKENJbxi,iv:5hnV5kRCNsOerK0UyxilXu9nS6HG/Jvau8l/8GzOTqQ=,tag:RaDub/YISrGnmQhIXmv3Qg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1h4wse77xcknyuzq798eg5cvl30npk5lxzk05cfwmpyhnz7vl39psqavxdm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UGhJRkw0RERkSUk4aGZY
            QmdjZVJRL1Y2YWdyV1ZUMGpUblBXc1djdEFrCjdHS2ZFU0pOWEZYOXRWSU1iTUZ3
            ek53NmxONWsyaCtzbFVLUkhSLzd1RE0KLS0tIExFTjhaM1ZvRHpXRGJlRzRDZEpS
            dVgwUjVUeVpnK3Z5dUtDRURWditISDAKsM+uaCE17g/36DNrfFWkep/y7Z067lWh
            UObWOT4JpcuYglA4N5zZc3SkOKOBYMeIRjUCULi6df6ECl2UttyfwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T18:54:51Z"
    mac: ENC[AES256_GCM,data:mGoS70FJjl/AxQyLu3NpLiZdSSAN4Dz0W6ScEcMVK7mSOjWyilPSAogU3qbLOav6kr+KCk9iSxjBjP+XIyzoe8PZJykid8PRAZjaYLRbGJ5t2MkWKWTMwWVOH/kONonIR0WDs0zWhiDuQ4BzA/DWd0OHjayTeVCQsP/O+9sMkBg=,iv:bxUSpram5hFfYLPgZyFJ5rhRN8Hg68wibc8ePz9BNhI=,tag:ki0u8Jr9fFmN52wkMcMhMQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
