apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hGMbJZdMYvE3Jhifp29MZAAptwIqs6xUaaaMNJzqWyG0rjIBqrYjJyzY/lgdAZfbzSIFEfAJtziczUkllukk9467rz+tKXVxeNJZDW/iEILHeBlsWu1x05cQJCiOnlVICw+3ESnPUrpwn9/us05nvKYrbZh5zHH0apjU4yZ0c9ZXiFQ3CFwKz7qylVtB9O3r0OU4PZQJoKyGwyFs92lhi3CC4OfbG6ZvV4p+Te65k5M73c8OKgl5Ne7g60fofhG06wpYHzgh9DA9cxRFZ0lvMIrOQjPuMbF9QfAumzcBNDmFxorBqb6NQcqEY25Co5ylXkOeJLaeAS9fe61/D9LdnN2cdUMK/v47M+OewydI8CmwofDU2lYrL/pSdJfw/std,iv:io4cSXTVU/vtNJu3jOHaAxAP4aGj5CwRr1tg63js9wU=,tag:iFwW++Em6Mi31zzNpjnnDQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:V9N2rQYSBa2mP5cAwRtxgJOL0eFrkKF6ltrjnxdhxv1VPU68/+0fffpqpE/baBB56s8khyKklCh/3vH9klnlV7KlUENnzRWXJoGfrasrKsJFQ1Hkx08slKhvTBcP8YqcC9SgBjlZUSycw/wkN8jAuJmkspbSrOkCIakrkkgg1qfkBjcfDxt47oA7Er27bwNvA1dVHFZGKVhFZyn7Tbx1s4oHoOAjbwVx3fcFgUJChfrFPJbPTU0zY7qG3gISokQp/tE3QT5aGghQwUBCxQ==,iv:kdec5DBEtyaA+E4eG6ljWhDILch4GrtKEERzWhFAXQY=,tag:EyRNVNeJzEM7+yStbCzy8Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:iohxEt5zto7RR116DQcpx8BT9rPvh2tmXGxL3+/XXJZPt5EDnjLdHHg/Lr5SkdqcOouFNniZmsHIDjcn83rX2tvR82zq/S8lQK9xsAEG2mU3kG9cm5Y7cUvaYP/bTuPVY2pHseGWCoxNl9DceOpImAKrC/pggREmjq1Jqd3Ya6cR9tMZtXA5t6+QXiIZEKNMGejYXjUo9Y1QjCNGyD7ScaHI+q2NEaap/6yF,iv:uudS/k/842jiU/evIW4pspQPPKJkHEaKgYik8FiJgvg=,tag:bjOc6Ic1y7wNubjAf9Wiog==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1h4wse77xcknyuzq798eg5cvl30npk5lxzk05cfwmpyhnz7vl39psqavxdm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbHQ5eGZ3Wk5DY01haVlx
            TmdYZjUxcGVyZThXdzA1dTM0VEJkYUdoZGlVClFCMEw4RnRsZGhhcUJPVWtkcXcv
            aXFYYXVFdEF4Tk9PZ0Z1dDlrTkQ1Z0UKLS0tIEhGWW9vQjNmRUdSZi90eGk5MEdJ
            K1drVGVzWnYvM2JZWlBveC9zS2thZHMKDvzk1S9ZcVADKTWoEzVyZMEQCVliEjE/
            l5KaBcUpEKUriRrBR7awp4udiPQPcAMjVxSc8j8Rwa2plOCtUjaNPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T15:17:10Z"
    mac: ENC[AES256_GCM,data:o5Wsj3IT1jEqHpTBTXdwbVPSG945tRbNT1I7uk6trQWFrH5q0dj5maEZXlsx02JDEPRpDiRBWz4iO4pb0HTfTCrviTDeecPWVecqMBXbKjc9DLnoBWBEJckzck8kmrOI8FFP0cnsDdVORcLkgWhX43TOSTSCuDZRLJ/FHsqlYVg=,iv:P3gyQ9Wq23iHrFTb53dEXhZTqjTJ4e17Q8+IhCDzA/M=,tag:4AsscEjh67/4VC6aBlmrPA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
